{{- if not .Values.hcloud.existingSecret }}
{{- $fullname := include "hcloud-metallb-controller.fullname" . -}}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ $fullname }}-apikey
type: kubernetes.io/basic-auth
data:
    apiKey: {{ .Values.hcloud.apiKey | b64enc | quote}}
---
{{- end }}